### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by FE-jw** [glenn2223/vscode-live-sass-compiler#193]
Is there a way to display only two decimal places?

33.3333333333% X
33.33% O

**Comment by glenn2223** [comment]
You need to round the output as below

```SCSS
@use 'sass:math';

.Test {
    width: math.div( math.round( math.div(100%, 3) * 100 ), 100)
}
```

**Comment by FE-jw** [comment]
Thanks your idea :)

**Comment by glenn2223** [comment]
You could also create your own function, as shown in the below usage (tweaked from [here](https://stackoverflow.com/a/34982673/3812374))

```scss
@use 'sass:math';

// In some function file somewhere
@function decimal-round ($number, $digits: 0, $mode: round) {
    $n: 1;
    // $number must be a number
    @if type-of($number) != number {
        @warn '#{ $number } is not a number.';
        @return $number;
    }
    // $digits must be a unitless number
    @if type-of($digits) != number {
        @warn '#{ $digits } is not a number.';
        @return $number;
    } @else if not unitless($digits) {
        @warn '#{ $digits } has a unit.';
        @return $number;
    }
    @if $digits > 0 {
        @for $i from 1 through $digits {
            $n: $n * 10;
        }
    }
    @if $mode == round {
        @return math.div(round($number * $n), $n);
    } @else if $mode == ceil {
        @return math.div(ceil($number * $n), $n);
    } @else if $mode == floor {
        @return math.div(floor($number * $n), $n);
    } @else {
        @warn '#{ $mode } is undefined keyword.';
        @return $number;
    }
}

.Test-Round {
    width: decimal-round(math.div(100%, 3), 2)
}

.Test-Ceil {
    width: decimal-round(math.div(100%, 3), 2, ceil)
}

.Test-Floor {
    width: decimal-round(math.div(100%, 3), 2, floor)
}
```

This will output: (format/spacing may be different)
```css
.Test-Round{width:33.33%}
.Test-Ceil{width:33.34%}
.Test-Floor{width:33.33%}
```
---

>ℹ - I'm using the `math.div` rule as divisions will be [deprecated in v2.0](https://sass-lang.com/documentation/breaking-changes/slash-div)
