### ISSUE TITLE
scss font import files removes the ()

### ISSUE THREAD

**Issue by DigitalTrading** [glenn2223/vscode-live-sass-compiler#208]
When I add this import into an scss file:
@import url("https://someimportdomain.com");
and then view the compiled css file it has removed the () around the url.

This is then preventing the import working. Can you advise what I am doing wrong?
Thanks
Roger

**Comment by glenn2223** [comment]
Sorry but I'm not able to replicate it.

I did see that, in compressed mode, it removes the `url` and brackets - which is allowed/valid[<sup>REF</sup>](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#syntax).

You could also try reinstalling the extension and checking there are no compilation errors. However, it's actually [sass/dart-sass](https://github.com/sass/dart-sass) that processes the compilation - so you could open an issue there.

---
### Tested code

**INPUT - SCSS**
```scss
@use '../partial/partial' as p;

@import url("https://someimportdomain.com");

.Test {
    color: p.$Color;
}
```

**OUTPUT - CSS (expanded)**
```css
@import url("https://someimportdomain.com");
.Test {
  color: pink;
}/*# sourceMappingURL=index.css.map */
```

**OUTPUT - CSS (compressed)**
```css
@import"https://someimportdomain.com";.Test{color:pink}/*# sourceMappingURL=index.css.map */
```
