### ISSUE TITLE
@use not compiling, @import does

### ISSUE THREAD

**Issue by chybeat** [glenn2223/vscode-live-sass-compiler#217]
Vars file (_vars.scss)
```SCSS
//Variables of colors
$main-backgound: #161619;
$main-font-color: #d6cece;
```

Main File (main.scss)
```SCSS
@use 'vars'

html {
	background-color: $main-backgound;
	color: $main-font-color;
	font-family: Sans-Serif;
	font-size: 16px;
	line-height: 1.5em;
}
```

On save ouput this:

```
Change detected - 8/25/2022, 4:37:18 PM
main.scss
--------------------
Compilation Error
Error: Undefined variable.
  ╷
4 │     background-color: $main-backgound;
  │                       ^^^^^^^^^^^^^^^
  ╵
  d:\{folder}\.dev\sass\main.scss 4:20  root stylesheet
--------------------
Watching...
--------------------
```

Changin `@use` to `@import` on `main.css` file:

```SCSS
@import 'vars'

html {
	background-color: $main-backgound;
	color: $main-font-color;
	font-family: Sans-Serif;
	font-size: 16px;
	line-height: 1.5em;
}

```
Is compiled!

```
Change detected - 8/25/2022, 4:40:16 PM
main.scss
--------------------
Generated:
d:\{folder}\css\main.css.map
d:\{folder}\css\main.css
```

So, may be I'm using wrong these SASS 'feature' (`@use`), reading about `@import` [here](https://sass-lang.com/documentation/at-rules/import) i'm FUD about `@import` and try `@use` with the extension. But I not have problem continue using `@import`...

**Comment by chybeat** [comment]
Ok, after read [this question](https://github.com/glenn2223/vscode-live-sass-compiler/issues/198) (and only to clarify the use of `@use` and namespaces), changing to next code on main.scss complies sucessfull:

```SCSS
@import 'vars'

html {
	background-color: vars.$main-backgound; // added 'vars' namespace to use the variable in _vars.scss file
	color: vars.$main-font-color; // added 'vars' namespace to use the variable in _vars.scss file
	font-family: Sans-Serif;
	font-size: 16px;
	line-height: 1.5em;
}
```


Please read the complete documentation [here](https://sass-lang.com/documentation/at-rules/use#loading-members) including the `Choice a namespace` section. Hope this helps!
