### ISSUE TITLE
Pseudo-element bug :  placeholder strange compilation

### ISSUE THREAD

**Issue by taupz** [glenn2223/vscode-live-sass-compiler#272]
Hi, im still a beginner so it's possible im wrong on some points.
I'll describe my issue because i'm not sure it's really a problem on every pseudo-element.

Here is my code (i'm trying to change placeholder font color) : 
```scss
.search-bar{
        border: 1px solid #ECEFF4;
        border-radius: 30px;

        input{
            height: 30px;
            width: 200px;

            ::-webkit-input-placeholder{
                color: blue;
            }
        }
    }
```
When i look in the compiled css file i have this for the placeholder
```scss
nav .search-bar input ::-webkit-input-placeholder {
  color: red;
}/*# sourceMappingURL=style.css.map */
```

There is an extra space between `input` and `::-webkit-input-placeholder` that needs to be removed for the selector to work correctly, because when i remove it manually it works (and it looks like this : `nav .search-bar input::-webkit-input-placeholder`)

Thats pretty much everything, i don't know if it was clear enough, and btw thanks for your extension it is really useful
