### ISSUE TITLE
Bug on pseudo class and pseudo elements

### ISSUE THREAD

**Issue by taupz** [glenn2223/vscode-live-sass-compiler#273]
### Bug on pseudo class and pseudo elements
Hi, im still a beginner so it's possible im wrong on some points.
I'll describe my issue because i'm not sure it's really a problem on every pseudo-element or pseudo class.

Here is my scss code (i'm trying to change placeholder font color) : 
```scss
.search-bar{
        input{
            ::-webkit-input-placeholder{
                color: blue;
            }
        }
    }
```
When i look in the compiled css file i have this for the placeholder
```css
nav .search-bar input ::-webkit-input-placeholder {
  color: red;
}/*# sourceMappingURL=style.css.map */
```

There is an extra space between `input` and `::-webkit-input-placeholder` that needs to be removed for the selector to work correctly, because when i remove it manually it works (and it looks like this : `nav .search-bar input::-webkit-input-placeholder`)

It is the same for hover

Thats pretty much everything, i don't know if it was clear enough, and btw thanks for your extension it is really useful
