### ISSUE TITLE
mixin error?

### ISSUE THREAD

**Issue by JanSzalanski** [glenn2223/vscode-live-sass-compiler#291]
I don't know if this is a bug on the plug-in side or if the syntax has changed? But in the first instance I got an error after changing from the Live Sass Compailer (Ritwick Dey), which VS pointed out to me as deprecated, to this Live Sass Compiler (Glenn Marks). The previous one I had created this mixin: 

```scss
$breakpoints: (
 small: (max-width: 640px),
  medium: (max-width: 800px),
 );

    @mixin mq($breakpoint)  {
       $size: map-get($breakpoints, $breakpoint);
        @if ($size) {
         @media #{$size} {
           @content;
         }
       } @else {
         @error '"#{$breakpoint}" - no such point'
       }
     }
```

And on the previous plugin the compilation ran without error and everything worked currently it returns me an error of this kind:

```diff
   Compilation Error
   Error: (max-width: 640px) isn't a valid CSS value.
       ╷
    5 │ @media ($size) {
       │                      ^^^^^
       ╵
```

It's been a while since I looked at this code has the syntax of sass itself changed in that time?

**Comment by glenn2223** [comment]
Must have been some update to SASS. Surround the values in quotes and it will work (as below)

**Input:**
```scss
$breakpoints: (
    small: "(max-width: 640px)",
    medium: "(max-width: 800px)",
);

@mixin mq($breakpoint) {
    $size: map-get($breakpoints, $breakpoint);

    @if ($size) {
        @media #{$size} {
            @content;
        }
    }

    @else {
        @error '"#{$breakpoint}" - no such point'
    }
}

.me {
    color: purple;
}

@include mq(small) {
    .me {
        color: pink
    }
}
```

**Output:**
```css
.me {
  color: purple;
}

@media (max-width: 640px) {
  .me {
    color: pink;
  }
}
```
