### ISSUE TITLE
Sass to CSS transpiling is not correct in some scenerios.

### ISSUE THREAD

**Issue by sufwansadiq** [glenn2223/vscode-live-sass-compiler#298]
Hi,
i have been using this extension for last 3 days and i have encountered two bugs in it.
My sass code is:
```SCSS
$main-color: cyan;
$secodary-color: #333;
$ter-color: pink;
$green-color: green;

$font-lg: 40px;
$font-md: 30px;
$font-sm: 40px;



// demonstrate mixin with an argument 
// accepting multiple parameters...
@mixin trans($param...) {
  transition: $param;
}
.navigation {
  background-color: $main-color;
  ul {
    list-style: none;
    display: flex;
    gap: $font-lg;
    padding: 10px;
  }
  a {
    text-decoration: none;
    &:link,&:visited {
      color: $green-color;
      @include trans(color 5s,background-color 5s);
    }
    &:hover,&:active {
      color: $ter-color;
      background-color: $green-color;
    }
  }
}

// demonstrate extend, common properties of both headings
// will be combined in one selector .heading and then that
// .heading slector will be @extend to the which ever heading 
// we want to include these styles

.heading {
  font-size: $font-lg;
  color: $secodary-color;
  background-color: $ter-color;
  text-align: center;
}
h1 {
  @extend .heading;
  &:hover {
    background-color: green;
  }
}

.foot h3 {
  @extend .heading;
  @extend .h1;
}
```

1. First issue: in the above the argument of @mixin, it accepts multiple parameters as indicated by three dots followed by argument "@mixin trans($param...)". However, if i remove these three dots and save sass file it produces no error. Steps to recreate error are: first save sass file with "@mixin trans($param...)" this code and look at css file. second step: save sass file with "@mixin trans($param)" this code and again look at css file, both times css file is same and compiler caught no error.
2. Second issue: in the last 2 selectors h1 and h3, steps to recreate the issue are: 1. first save sass file with h1 as class slector (.h1) and save, the resultant css file contains corresponding styles in .h1 selecor. 2. then modify sass file by converting .h1 to element slector i.e., h1 and save. now look at the resultant css file, it is the same as it was and have no effect on it for the second change (.h1--->h1)..
Thanks
Safwan
