### ISSUE TITLE
Variables not processed in container query declaration

### ISSUE THREAD

**Issue by jwrobbs** [glenn2223/vscode-live-sass-compiler#361]
I don't know if this is an extension issue or what.

SCSS variables aren't processed in the initial container query line. They're processed before and after it. They're processed in media queries. 

If I use #{$example_var}, the value is inserted, but any math isn't computed. Not hard to get around. But I don't know if that is how it's supposed to work.

Here is a very arbitrary example.

SCSS:
```
$example_var: 18;

h1 {
	font-size: $example_var * 2;

	@media (min-width: ($example_var * 70)) {
		font-size: $example_var + 1;
	}
	@container (min-width: (#{$example_var} * 70)) {
		font-size: $example_var;
	}
	@container (min-width: ($example_var * 70)) {
		font-size: $example_var;
	}
}
```

CSS:
```
h1 {
	font-size: 36;
}
@media (min-width: 1260) {
	h1 {
		font-size: 19;
	}
}
@container (min-width: (18 * 70)) {
	h1 {
		font-size: 18;
	}
}
@container (min-width: ($example_var * 70)) {
	h1 {
		font-size: 18;
	}
}/*# sourceMappingURL=test.css.map */
```

**Comment by glenn2223** [comment]
I'm afraid it's a user/SASS-progression issue. If you place your above code into the SASS Playground (https://sass-lang.com/playground), you get the output you provided above

If you're planning to do maths in that element, you need to do it within the SASS `#{  }` call - as below:

```SCSS
$example_var: 18;

h1 {
	font-size: $example_var * 2;

	@media (min-width: ($example_var * 70)) {
		font-size: $example_var + 1;
	}
	@container (min-width: (#{$example_var * 70})) {
		font-size: $example_var;
	}
	@container (min-width: (#{$example_var * 70})) {
		font-size: $example_var;
	}
}
````

Container calls aren't processed in the same way as media calls

---

You can raise is with the [sass/sass](//www.github.com/sass/sass) team and see if they can change it

Closing as not an extension issue
