### ISSUE TITLE
Compiled SCSS Multiline comments misplacement

### ISSUE THREAD

**Issue by Grant-Kellie** [glenn2223/vscode-live-sass-compiler#368]
# Compiled SCSS Multiline comments misplacement

## Issue
Comments in SCSS do not correspond to the correct position in CSS, when compiled create a wall of multiline comments, followed by the correct markdown.

## Notes
Live Sass Compiler v6.1.2

### SCSS
```SCSS
/*
@title: Image Overlay
@description: provides a darkened overlay effect, modifiers are available to change the positioning of internal content
*/
.overlay {
    width: calc(100% - 32px);
    height: 100%;    
    padding:0 16px;
    color: color.set('light');
    background: #0f0f0f;
    display:flex;
    flex-direction: column;
    justify-content:end;
    position: absolute;
    z-index:1;

    &:hover{
        background: #f0f0f0;
    }

    /*
    @group: Overlay size & position
    @title: Auto
    @description: 
    */
    &--auto { 
        height: auto;
    }

    /*
    @title: Quarter
    @description: 
    */
    &--quart {
        max-height: 25% !important;
    }
}
```
    
 ### Compiled CSS
```CSS
/*
@title: Image Overlay
@description: provides a darkened overlay effect, modifiers are available to change the positioning of internal content
*/
.overlay {
	width: calc(100% - 32px);
	height: 100%;
	padding: 0 16px;
	color: hsl(0, 0%, 100%);
	background: hsla(206, 11%, 7%, 0.75);
	display: flex;
	flex-direction: column;
	justify-content: end;
	position: absolute;
	z-index: 1;
	/*
	@group: Overlay size & position
	@title: Auto
	@description: 
	*/
	/*
	@title: Quarter
	@description: 
	*/
}

.overlay:hover {
	background: hsla(0, 0%, 0%, 0);
}
.overlay--auto {
	height: auto;
}
```
