### ISSUE TITLE
 complier converts scss hex value to unicode character in css

### ISSUE THREAD

**Issue by lbj** [glenn2223/vscode-live-sass-compiler#39]
The following code in my _style.scss file: 

``` {
       content: '\25BC';
.... }
```
becomes : 

``` {
       content: "▼";
.... }
```
when compiled to css.
Is there any way to prevent this? (Version v4.4.1 running on VS code on windows 10)

**Comment by glenn2223** [comment]
This is a known issue ([ref here](https://github.com/sass/sass/issues/1395))

There is a workaround [here](https://stackoverflow.com/a/30421654/3812374) (as per below)

SCSS
```scss
@function unicode($str)
{
  @return unquote("\"")+unquote(str-insert($str, "\\", 1))+unquote("\"");
}

.icon-ok {
    &:before {
      content: "\e601"; // BROKEN
    }
    &:after {
      content: unicode("e601"); // WORKS
    }
}
```

SASS
```sass
@function unicode($str)
  @return unquote("\"")+unquote(str-insert($str, "\\", 1))+unquote("\"")

.icon-ok
  &:before
    content: "\e601" // BROKEN
  &:after
    content: unicode("e601") // WORKS
```
