### ISSUE TITLE
Assigning SCSS variables to CSS variables doesn't compile

### ISSUE THREAD

**Issue by adamerose** [glenn2223/vscode-live-sass-compiler#83]
SCSS being compiled:
```scss
body {
  $brand-color: red;
  --primary-color: $brand-color;
  background-color: var(--primary-color);
}
```

Extension compilation output:
```scss
body {
  --primary-color: $brand-color;
  background-color: var(--primary-color);
}
```

Expected output:
```css
body {
  --primary-color: red;
  background-color: var(--primary-color);
}
```
